<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>h3_Your delivery address</name>
   <tag></tag>
   <elementGuidId>bc428a84-9ce4-4e11-949a-9457c13869a0</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//ul[@id='address_delivery']/li/h3</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>h3.page-subheading</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=heading[name=&quot;Your delivery address&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>h3</value>
      <webElementGuid>61e3a71f-8c7f-4689-9e23-50f32284f0d6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>page-subheading</value>
      <webElementGuid>c9df411e-c0d6-4f39-ae27-f5d0c3570bce</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Your delivery address</value>
      <webElementGuid>8061d7f5-7d75-48da-83b1-69c07fe1849e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;address_delivery&quot;)/li[@class=&quot;address_title&quot;]/h3[@class=&quot;page-subheading&quot;]</value>
      <webElementGuid>6461d9b4-016b-4818-af94-42383c3c65cd</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//ul[@id='address_delivery']/li/h3</value>
      <webElementGuid>b6a0eeaa-efa5-4713-94b5-9b9c86b91852</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Address Details'])[1]/following::h3[1]</value>
      <webElementGuid>3586e767-5d07-4e32-9d0b-f1a845e684e0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Checkout'])[1]/following::h3[1]</value>
      <webElementGuid>7058f924-59e9-4fa2-b0c0-aaeadc85d90c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Mr. AK Test'])[1]/preceding::h3[1]</value>
      <webElementGuid>a65cfb39-665c-4046-a707-c901a6ce3a5a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Genda Circle'])[1]/preceding::h3[1]</value>
      <webElementGuid>d2b46114-f72e-4e0b-a350-6dac29e14899</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Your delivery address']/parent::*</value>
      <webElementGuid>5874e946-4b1f-45de-ada6-4fd4408296ca</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//h3</value>
      <webElementGuid>1463f5ba-32e8-4245-bb39-34a05ff4a148</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//h3[(text() = 'Your delivery address' or . = 'Your delivery address')]</value>
      <webElementGuid>d9a24fdf-a16e-42d4-bbad-55e6ea2a3f54</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
