<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>product_1_total</name>
   <tag></tag>
   <elementGuidId>0426a50d-cdaa-4013-ad82-2b9b8fe88c1b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//tr[@id='product-1']/td[5]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>td.cart_total</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=cell[name=&quot;Rs. 500&quot;i] >> nth=1</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>td</value>
      <webElementGuid>62376549-cc7c-464f-aced-b69ee047afae</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>cart_total</value>
      <webElementGuid>a4c6f61f-9498-4984-9fb7-a3906b897207</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
								Rs. 500
							</value>
      <webElementGuid>c77219e6-89fb-4a2c-9a72-ad16d1fbab52</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;product-1&quot;)/td[@class=&quot;cart_total&quot;]</value>
      <webElementGuid>72f4ea68-95cf-46ca-b495-3c6689fef224</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//tr[@id='product-1']/td[5]</value>
      <webElementGuid>90c63273-60fa-4872-87b4-c28e48deb468</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Blue Top'])[1]/following::td[3]</value>
      <webElementGuid>9987ec63-50b7-4833-81c1-f581e430600a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Total'])[1]/following::td[6]</value>
      <webElementGuid>2d4bff4c-27ef-4de3-8139-fef82bd02d6c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Men Tshirt'])[1]/preceding::td[3]</value>
      <webElementGuid>f7c74940-e040-412d-a872-d30ea45e6df8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Cart is empty!'])[1]/preceding::td[8]</value>
      <webElementGuid>2298ac3c-f761-4c20-a84e-6c3b279b0a15</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tbody/tr/td[5]</value>
      <webElementGuid>230dc57f-ad2d-4789-af4a-87edad647b20</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//td[(text() = '
								Rs. 500
							' or . = '
								Rs. 500
							')]</value>
      <webElementGuid>e1818ce3-46de-4a35-bd1f-395c28ad796a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
